using System;

namespace Dpr.Battle.Logic
{
    public enum ContFlag
    {
        CONTFLG_ACTION_DONE,
        CONTFLG_CANT_CHANGE,
        CONTFLG_TAME,
        CONTFLG_SORAWOTOBU,
        CONTFLG_DIVING,
        CONTFLG_ANAWOHORU,
        CONTFLG_SHADOWDIVE,
        CONTFLG_MARUKUNARU,
        CONTFLG_TIISAKUNARU,
        CONTFLG_KIAIDAME,
        CONTFLG_POWERTRICK,
        CONTFLG_MIKURUNOMI,
        CONTFLG_CANT_ACTION,
        CONTFLG_MORAIBI,
        CONTFLG_BATONTOUCH,
        CONTFLG_ITEM_LOSE,
        CONTFLG_ELECFIELD_GUARD,
        CONTFLG_MISTFIELD_GUARD,
        CONTFLG_ONNEN,
        CONTFLG_MITIDURE,
        CONTFLG_JUDEN,
        CONTFLG_GAMAN,
        CONTFLG_BODYPURGE,
        CONTFLG_MOETUKIRU,
        CONTFLG_HAISUINOZIN,
        CONTFLG_MAX,
        CONTFLG_NULL = 25
    }
}
