using System;

namespace Dpr.Battle.View
{
    public enum BattleConstantKey
    {
        WAIT_CAMERA_CHECK_GROUND_Y_POKEMON,
        WAIT_CAMERA_CHECK_GROUND_Y_TRAINER,
        MSG_WINDOW_WAZA_MSG_AUTO_HIDE_FRAME,
        SEQ_GAUDE_DAMAGE_SE_NORMAL,
        SEQ_GAUDE_DAMAGE_SE_ADVANTAGE,
        SEQ_GAUDE_DAMAGE_SE_DISADVANTAGE,
        SEQ_GAUDE_DAMAGE_SE_NONE,
        SEQ_HIT_BACK_LENGTH,
        SEQ_HIT_BACK_BACK_FRAME,
        SEQ_HIT_BACK_RETURN_FRAME,
        SEQ_HIT_BACK_NOT_DEFAULT_CAMERA_PLACE_BACK_FRAME,
        SEQ_PLAY_POKEMON_DEAD_ACT_WILD,
        SEQ_PLAY_POKEMON_DEAD_ACT_OTHER,
        SEQ_PLAY_MEMBER_OUT,
        SEQ_PLAY_TRAINER_THROW_BALL_SINGLE_WILD,
        POKE_LANDING_REMAING_TIME_TO_LAND_B01,
        POKE_LANDING_REMAING_TIME_TO_WAIT,
        POKE_LANDING_POKE_FALL_FRAME,
        POKE_LANDING_POKE_FALL_EASING,
        POKE_LANDING_POLE_SCALE_FRAME,
        DEFAULT_INTRO_SEQUENCE_FILE,
        DEFAULT_MEMBER_CHANGE_ACT_SEQUENCE_FILE,
        PLAY_WAIT_CAMERA_DELAY_FRAME,
        START_DELAY_FADE_CNT,
        LANDING_SOUND_REGISTER,
        LANDING_SWITCH_GROUP,
        LANDING_HEAVY_EFFECT,
        LANDING_LIGHTHEAVY_EFFECT,
        DEFAULT_POST_DOF_FOCAL_LENGTH,
        DEFAULT_POST_DOF_FAR_DEPTH,
        DEFAULT_POST_DOF_DISTANCE,
        TUTORIAL_BATTLE_ENTRY_MOTION,
        DOF_SENSOR_SCALE_MORNING,
        DOF_SENSOR_SCALE_DAYTIME,
        DOF_SENSOR_SCALE_EVENING,
        DOF_SENSOR_SCALE_NIGHT,
        DOF_SENSOR_SCALE_MIDNIGHT,
        EX_GIRATHINA_ASSET_NAME
    }
}
