using System;

namespace Dpr.Battle.View
{
    public enum BattleSetupIntroID
    {
        THROW_PLAYER_SINGLE,
        THROW_PLAYER_SINGLE_FAST,
        THROW_PLAYER_DOUBLE_EXIST_FRIEND,
        THROW_PLAYER_DOUBLE_NOT_EXIST_FRIEND,
        THROW_ENEMY_SINGLE,
        THROW_ENEMY_SINGLE_COMM,
        THROW_ENEMY_DOUBLE_IS_MULTI,
        THROW_ENEMY_DOUBLE_IS_MULTI_COMM,
        THROW_ENEMY_DOUBLE,
        THROW_ENEMY_DOUBLE_COMM,
        THROW_PLAYER_SINGLE_TUREARUKI,
        THROW_PLAYER_SINGLE_HAPPY_A,
        THROW_PLAYER_SINGLE_HAPPY_B,
        THROW_PLAYER_SINGLE_HAPPY_C,
        THROW_PLAYER_SINGLE_HATE,
        THROW_ENEMY_SINGLE_HEROINE
    }
}
